name: cosmos-wind-cnn
channels:
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - numpy
  - scipy
  - pandas
  - xarray
  - netcdf4
  - scikit-learn
  - metpy
  - dask
  - fsspec
  - intake
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - pyproj
  - cartopy
  - tensorboard
  - jupyter
  - ipython
  - pytest
  - requests
  - aiohttp
  - intake-xarray
  - zarr
  - s3fs

  - pip
  - pip:
      - -e .